# Generated by Django 5.2.1 on 2025-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_faceprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceprofile",
            name="face_encoding",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
